import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../styles/globals.css';

const routes = ['/', '/login', '/signup', '/appraiser', '/agent'];
function navigate(path){ window.history.pushState({}, '', path); window.dispatchEvent(new Event('popstate')); window.scrollTo({top:0,behavior:'smooth'}); }
function usePath(){ const [path,setPath]=useState(location.pathname); useEffect(()=>{const fn=()=>setPath(location.pathname); addEventListener('popstate',fn); return()=>removeEventListener('popstate',fn)},[]); return routes.some(r=>path===r||path.startsWith('/appraiser/')||path.startsWith('/agent/'))?path:'/'; }
function Link({to, children, className}){ return <a href={to} className={className} onClick={e=>{e.preventDefault(); navigate(to)}}>{children}</a> }
function Logo({compact=false}){return <div className="logo-lockup"><div className="logo-mark"><span>V</span></div>{!compact&&<div><strong>Valora<span>IQ</span></strong><small>Real Estate Intelligence</small></div>}</div>}

function PublicNav(){return <header className="public-nav"><Link to="/" className="plain"><Logo/></Link><nav><a href="/#workflows">Workflows</a><a href="/#features">Features</a><a href="/#pricing">Pricing</a><Link to="/login">Log in</Link><Link className="btn small gold" to="/signup">Start free</Link></nav></header>}
function Landing(){return <><PublicNav/><main><section className="hero"><div className="hero-grid"><div><p className="eyebrow">Professional Real Estate Intelligence Workspace</p><h1>One platform. Two workflows. Cleaner real estate decisions.</h1><p className="hero-copy">ValoraIQ helps appraisers build defensible valuation support and helps agents create persuasive CMA and listing presentations from the same market intelligence engine.</p><div className="hero-actions"><Link className="btn gold" to="/signup">Start building →</Link><Link className="btn glass" to="/appraiser">View demo dashboard</Link></div></div><div className="hero-preview"><div className="preview-header"><span/><span/><span/></div><div className="preview-title">Market Snapshot</div><div className="metric-grid three"><div><b>$425k</b><span>Median Sold</span></div><div><b>18</b><span>DOM</span></div><div><b>97.4%</b><span>List/Sale</span></div></div><div className="fake-chart">{[42,55,48,68,61,78,90].map(h=><i key={h} style={{height:`${h}%`}}/> )}</div><div className="preview-card"><b>Professional-use positioning</b><span>Market evidence, workflow support, and presentation outputs without replacing professional judgment.</span></div></div></div></section><section className="section" id="workflows"><p className="eyebrow center">Persona-specific dashboards</p><h2>Appraisers and agents should not see the same product.</h2><div className="workflow-cards"><article><h3>Appraiser Workspace</h3><p>Subject, MLS import, market conditions, comp selection, adjustment grid, reconciliation, narrative, exhibits, and workfile export.</p><Link to="/appraiser">Open appraiser demo</Link></article><article><h3>Agent/Broker Workspace</h3><p>Property overview, market snapshot, pricing strategy, active/pending/sold intelligence, seller net sheet, renovation ROI, listing presentation, and CMA export.</p><Link to="/agent">Open agent demo</Link></article></div></section><section className="section" id="features"><p className="eyebrow center">Core platform</p><h2>From raw MLS data to clear, client-ready outputs.</h2><div className="feature-grid">{['MLS Import','Market Intelligence','Professional Reports','AI Workflow Support'].map(t=><div className="feature-card" key={t}><div className="glyph">✦</div><h3>{t}</h3><p>Premium workflow support designed for real estate professionals.</p></div>)}</div></section><section className="section pricing" id="pricing"><p className="eyebrow center">Pricing preview</p><h2>Start with the workflow. Add cloud accounts next.</h2><p className="muted max center-block">Auth, database persistence, billing, teams, and saved cloud projects are ready for the next Supabase phase.</p></section></main></>}
function Auth({type}){return <><PublicNav/><main className="auth-page"><section className="auth-card"><p className="eyebrow">{type==='login'?'Welcome back':'Start free'}</p><h1>{type==='login'?'Log in to ValoraIQ':'Create your workspace'}</h1>{type==='signup'&&<input placeholder="Name"/>}<input placeholder="Email"/><input placeholder="Password" type="password"/><button className="btn gold full" onClick={()=>navigate(type==='login'?'/appraiser':'/agent')}>{type==='login'?'Continue to demo workspace':'Create demo workspace'}</button><p className="muted">Supabase auth will replace this prototype screen in the next phase.</p></section></main></>}

const appraiserTabs=['Dashboard','Projects','Subject Property','MLS Import','Market Conditions','Comp Selection','Adjustment Grid','Reconciliation','Narrative','Photos / Exhibits','AI Assistant','Export Workfile'];
const agentTabs=['Dashboard','Projects','Property Overview','MLS Import','Market Snapshot','Pricing Strategy','Seller Net Sheet','Renovation ROI','Listing Presentation','Photos','AI Assistant','CMA Export'];
function slug(s){return s.toLowerCase().replace(/\/|&/g,'').replace(/\s+/g,'-')}
function DashboardShell({persona}){const [tab,setTab]=useState('Dashboard'); const [collapsed,setCollapsed]=useState(false); const isAppraiser=persona==='appraiser'; const tabs=isAppraiser?appraiserTabs:agentTabs; useEffect(()=>{const parts=location.pathname.split('/'); if(parts[2]){const match=tabs.find(t=>slug(t)===parts[2]); if(match) setTab(match)}},[persona]); function setRoute(t){setTab(t); window.history.pushState({},'',`/${persona}${t==='Dashboard'?'':'/'+slug(t)}`)} return <div className={`dashboard-shell ${collapsed?'is-collapsed':''}`}><aside className="sidebar"><Logo compact={collapsed}/><div className="mode-toggle"><button className={isAppraiser?'active':''} onClick={()=>navigate('/appraiser')}>Appraiser</button><button className={!isAppraiser?'active':''} onClick={()=>navigate('/agent')}>Agent/Broker</button></div><div className="nav-section-label">{isAppraiser?'Appraiser Workflow':'Agent Workflow'}</div><nav className="side-nav">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setRoute(t)}><span className="nav-icon">{iconFor(t)}</span><span>{t}</span></button>)}</nav><button className="collapse-btn" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'Expand':'Collapse'} sidebar</button></aside><main className="dashboard-main"><header className="topbar"><button className="icon-btn" onClick={()=>setCollapsed(v=>!v)}>☰</button><div><strong>{isAppraiser?'Appraiser Workspace':'Agent/Broker Workspace'}</strong><span>{isAppraiser?'Defensible valuation support':'Listing and pricing intelligence'}</span></div><div className="topbar-actions"><button className="btn ghost">Help</button><button className="avatar">VQ</button></div></header><Workspace persona={persona} tab={tab}/></main></div>}
function iconFor(t){ if(t.includes('Import')) return '⬆'; if(t.includes('Market')) return '↗'; if(t.includes('Export')) return '⇩'; if(t.includes('Project')) return '▣'; if(t.includes('AI')) return '✦'; if(t.includes('Photo')) return '◉'; if(t.includes('Net')) return '$'; return '⌂'; }
function KPI({label,value,helper}){return <div className="kpi"><div className="kpi-icon">✦</div><div><span>{label}</span><strong>{value}</strong><small>{helper}</small></div></div>}
function Workspace({persona,tab}){ if(tab==='Dashboard') return persona==='appraiser'?<AppraiserHome/>:<AgentHome/>; if(tab==='Projects') return <Projects persona={persona}/>; if(tab.includes('Import')) return <ImportData persona={persona}/>; if(tab.includes('Market')) return <Market persona={persona}/>; if(tab==='Adjustment Grid') return <Adjustments/>; if(tab==='Reconciliation') return <Panel title="Reconciliation" eyebrow="Appraiser Only" copy="Review adjusted sale range, comp reliability, gross/net adjustment ratios, and final opinion support." metrics={['$421k Low','$438k Weighted','$452k High']}/>; if(tab==='Narrative') return <Narrative/>; if(tab.includes('Pricing')) return <Pricing/>; if(tab.includes('Seller Net')) return <SellerNet/>; if(tab.includes('Renovation')) return <Panel title="Renovation ROI" eyebrow="Agent Only" copy="Compare potential pricing lift from common pre-list improvements against estimated cost and market appeal."/>; if(tab.includes('Presentation')) return <ExportLike title="Seller Presentation Builder" items={['Market Snapshot','Pricing Strategy','Seller Net Sheet','Renovation ROI']}/>; if(tab.includes('Photo')) return <Photos persona={persona}/>; if(tab.includes('AI')) return <Assistant persona={persona}/>; if(tab.includes('Export')||tab.includes('CMA')) return <ExportLike title={persona==='appraiser'?'Workfile Export':'CMA & Presentation Export'} items={persona==='appraiser'?['Subject Summary','Market Conditions','Adjustment Grid','Reconciliation','Narrative Addendum','Photo Exhibits']:['Seller Presentation','CMA Summary','Pricing Strategy','Seller Net Sheet','Renovation ROI','Comp Pages']}/>; return <Panel title={tab} eyebrow="Workspace" copy="This page is now separated by persona and ready for the Supabase persistence phase."/> }
function AppraiserHome(){return <div className="dash-page"><section className="welcome"><p className="eyebrow">Good morning</p><h1>Appraiser intelligence workspace</h1><p>Build support for market conditions, comparable selection, adjustments, reconciliation, and workfile exports.</p></section><div className="kpi-row"><KPI label="Active Projects" value="7" helper="2 due this week"/><KPI label="Data Sets Imported" value="12" helper="MLS CSVs structured"/><KPI label="Reports Generated" value="9" helper="workfile PDFs"/><KPI label="Last Market Study" value="May 18" helper="median trend updated"/></div><div className="two-col"><ProjectTable/><QuickActions persona="appraiser"/></div><section className="panel-card"><h2>Professional Use Only</h2><p className="muted">ValoraIQ organizes evidence and valuation support. Appraisers remain responsible for scope of work, reconciliation, and appraisal conclusions.</p></section></div>}
function AgentHome(){return <div className="dash-page"><section className="welcome"><p className="eyebrow">Listing intelligence</p><h1>Agent and broker workspace</h1><p>Turn MLS data into market snapshots, pricing strategy, net sheets, renovation ROI, and seller presentations.</p></section><div className="kpi-row"><KPI label="Active CMAs" value="5" helper="seller consultations"/><KPI label="Hot Markets" value="3" helper="low inventory"/><KPI label="Avg Net Impact" value="$18.4k" helper="concession scenarios"/><KPI label="Presentations" value="14" helper="listing packets"/></div><div className="two-col"><ProjectTable/><QuickActions persona="agent"/></div><Pricing compact/></div>}
function ProjectTable(){const rows=[['123 Maple Street','Appraisal','In Progress','$425,000'],['456 Oak Avenue','CMA','Review','$512,000'],['789 Pine Road','Market Study','Draft','$390,000']]; return <div className="table-card"><div className="card-head"><h2>Recent Projects</h2><button className="btn ghost">View all</button></div><table><thead><tr><th>Project</th><th>Type</th><th>Status</th><th>Indication</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b><span>Updated recently</span></td><td>{r[1]}</td><td><em>{r[2]}</em></td><td>{r[3]}</td></tr>)}</tbody></table></div>}
function QuickActions({persona}){const actions=persona==='appraiser'?['New Appraisal Project','Import MLS Data','Run Market Conditions','Export Workfile PDF']:['New CMA Project','Import MLS Data','Build Seller Presentation','Create Seller Net Sheet']; return <div className="quick-card"><h2>Quick Actions</h2>{actions.map(a=><button key={a}>{a}<span>›</span></button>)}</div>}
function Projects({persona}){const projects=['123 Maple Street','456 Oak Avenue','789 Pine Road','321 Elm Drive','654 Cedar Lane']; return <div className="dash-page"><section className="panel-card row-between"><div><p className="eyebrow">Projects</p><h1>{persona==='appraiser'?'Appraisal Projects':'CMA & Listing Projects'}</h1><p className="muted max">Local project cards are ready now. Supabase will later persist projects, uploads, notes, exports, and team access.</p></div><button className="btn gold">+ New Project</button></section><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p}><span>{persona==='appraiser'?'Appraisal':i%2?'Listing CMA':'Seller Strategy'}</span><h3>{p}</h3><p>Updated {i+1} day{i?'s':''} ago</p><div><em>{i%3===0?'In Progress':i%3===1?'Review':'Draft'}</em><button className="btn ghost small">Open</button></div></article>)}</div></div>}
function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean); const headers=(lines.shift()||'').split(',').map(x=>x.trim().replace(/^"|"$/g,'')); return lines.map(l=>{const cells=l.split(',').map(x=>x.trim().replace(/^"|"$/g,'')); return Object.fromEntries(headers.map((h,i)=>[h,cells[i]||'']))})}
function normalize(row){const pick=(...ks)=>ks.map(k=>row[k]).find(Boolean)||''; const num=v=>Number(String(v).replace(/[$,]/g,''))||0; return {address:pick('address','Address','Property Address'),status:pick('status','Status','MLS Status')||'Sold',price:num(pick('sale_price','Sale Price','Close Price','Sold Price')),gla:num(pick('gla','GLA','Sq Ft','Living Area')),dom:num(pick('dom','DOM','Days on Market'))}}
function ImportData({persona}){const [rows,setRows]=useState([]); async function handle(e){const f=e.target.files?.[0]; if(!f)return; const text=await f.text(); setRows(parseCSV(text).map(normalize).filter(r=>r.address||r.price))} return <div className="dash-page"><section className="panel-card"><p className="eyebrow">MLS Import</p><h1>{persona==='appraiser'?'Import appraisal sales data':'Import CMA market data'}</h1><p className="muted max">CSV import is wired for Vite and ready for MLS exports. PapaParse can be added later if you want deeper edge-case support.</p><label className="upload-box"><strong>Click to upload MLS CSV</strong><span>Active, pending, sold, expired, or closed sales exports</span><input type="file" accept=".csv" onChange={handle}/></label></section>{rows.length>0&&<section className="table-card"><div className="card-head"><h2>Imported Records</h2><span>{rows.length} rows detected</span></div><table><thead><tr><th>Address</th><th>Status</th><th>Price</th><th>GLA</th><th>DOM</th></tr></thead><tbody>{rows.slice(0,12).map((r,i)=><tr key={i}><td>{r.address||'—'}</td><td>{r.status}</td><td>{money(r.price)}</td><td>{r.gla||'—'}</td><td>{r.dom}</td></tr>)}</tbody></table></section>}</div>}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0)}
function Market({persona}){const vals=[['$455k','Active Median'],['$441k','Pending Median'],['$425k','Sold Median'],['18','Median DOM']]; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Market Intelligence</p><h1>{persona==='agent'?'Active / Pending / Sold Analysis':'Market Conditions Study'}</h1><p className="muted max">Compare active competition, pending market direction, and closed-sale proof.</p><div className="metric-grid four">{vals.map(v=><div key={v[1]}><b>{v[0]}</b><span>{v[1]}</span></div>)}</div></section><section className="chart-card"><h2>Median Price Trend</h2><div className="line-chart">{[40,48,44,62,58,75,82].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div></section></div>}
function Adjustments(){const lines=['Location','Site','GLA','Quality','Condition','Garage','Basement','Concessions','Market Conditions']; const [values,setValues]=useState(Object.fromEntries(lines.map(l=>[l,0]))); const total=useMemo(()=>Object.values(values).reduce((a,b)=>a+Number(b||0),0),[values]); return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Appraiser Only</p><h1>Adjustment Grid</h1><p className="muted max">Line-item support, notes, net/gross indicators, and reconciliation-ready totals.</p></section><section className="table-card"><table><thead><tr><th>Adjustment Line</th><th>Amount</th><th>Support Note</th></tr></thead><tbody>{lines.map(l=><tr key={l}><td>{l}</td><td><input className="cell-input" type="number" value={values[l]} onChange={e=>setValues({...values,[l]:e.target.value})}/></td><td><input className="cell-input wide" placeholder="Market-derived support or paired-sale note"/></td></tr>)}</tbody></table><div className="adjustment-total">Net Adjustment: <strong>{money(total)}</strong></div></section></div>}
function Panel({title,eyebrow,copy,metrics}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted max">{copy}</p>{metrics&&<div className="metric-grid three">{metrics.map(m=><div key={m}><b>{m.split(' ')[0]}</b><span>{m.split(' ').slice(1).join(' ')}</span></div>)}</div>}</section></div>}
function Narrative(){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Appraiser Only</p><h1>Narrative Builder</h1><p className="muted max">Generate editable report language for market conditions, comp selection, concessions, reconciliation, and data quality.</p><textarea className="big-text" defaultValue="The comparable sales selected represent the best available market evidence based on proximity, date of sale, physical similarity, and overall reliability."/></section></div>}
function Pricing({compact=false}){return <section className={`strategy-card ${compact?'':'large'}`}><p className="eyebrow">Agent Only</p><h1>Pricing Strategy Snapshot</h1><div className="metric-grid three"><div><b>$510k</b><span>Recommended List</span></div><div><b>$495k–$525k</b><span>Likely Contract Range</span></div><div><b>14–21</b><span>Expected DOM</span></div></div><p>Position pricing slightly below current active competition while staying aligned with pending momentum and closed-sale proof.</p></section>}
function SellerNet(){const [price,setPrice]=useState(510000),[mort,setMort]=useState(310000),[comm,setComm]=useState(5.5),[cost,setCost]=useState(6500); const net=price-mort-(price*comm/100)-cost; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Agent Only</p><h1>Seller Net Sheet</h1><div className="form-grid"><label>Sale Price<input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Mortgage Payoff<input type="number" value={mort} onChange={e=>setMort(+e.target.value)}/></label><label>Commission %<input type="number" value={comm} onChange={e=>setComm(+e.target.value)}/></label><label>Closing Costs<input type="number" value={cost} onChange={e=>setCost(+e.target.value)}/></label></div><div className="net-result">Estimated Seller Net <strong>{money(net)}</strong></div></section></div>}
function ExportLike({title,items}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Export Center</p><h1>{title}</h1><p className="muted max">PDF export preview is structured. Final branded PDF generation can be upgraded after backend setup.</p><div className="check-list">{items.map(i=><label key={i}><input type="checkbox" defaultChecked/> {i}</label>)}</div><button className="btn gold">Generate Preview Export</button></section></div>}
function Photos({persona}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Photos & Exhibits</p><h1>{persona==='appraiser'?'Subject and Comp Exhibits':'Listing Photo Organizer'}</h1><p className="muted max">Drag/drop UI is ready. Supabase Storage will later store images securely by project.</p><div className="photo-grid">{['Subject Front','Kitchen','Comparable 1','Map Exhibit'].map(x=><div className="photo-tile" key={x}><span>◉</span><b>{x}</b></div>)}</div></section></div>}
function Assistant({persona}){const prompts=persona==='appraiser'?['Draft market conditions narrative','Summarize concession evidence','Identify outlier comps','Explain reconciliation support']:['Create seller talking points','Explain pricing strategy','Summarize active competition','Write listing presentation intro']; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">AI Workflow Assistant</p><h1>{persona==='appraiser'?'Narrative and evidence support':'Seller conversation support'}</h1><p className="muted max">Positioned as workflow assistance, not automated valuation or appraisal replacement.</p><div className="prompt-grid">{prompts.map(p=><button key={p}>{p}</button>)}</div><textarea className="big-text" placeholder="Ask ValoraIQ to summarize evidence, explain a pricing position, or draft editable language..."/></section></div>}
function App(){const path=usePath(); if(path==='/login') return <Auth type="login"/>; if(path==='/signup') return <Auth type="signup"/>; if(path.startsWith('/appraiser')) return <DashboardShell persona="appraiser"/>; if(path.startsWith('/agent')) return <DashboardShell persona="agent"/>; return <Landing/>}

createRoot(document.getElementById('root')).render(<App/>);
