import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../styles/globals.css';

const routes = ['/', '/login', '/signup', '/appraiser', '/agent'];
function navigate(path){ window.history.pushState({}, '', path); window.dispatchEvent(new Event('popstate')); if(!path.includes('/appraiser/') && !path.includes('/agent/')) window.scrollTo({top:0,behavior:'smooth'}); }
function usePath(){ const [path,setPath]=useState(location.pathname); useEffect(()=>{const fn=()=>setPath(location.pathname); addEventListener('popstate',fn); return()=>removeEventListener('popstate',fn)},[]); return routes.some(r=>path===r||path.startsWith('/appraiser/')||path.startsWith('/agent/'))?path:'/'; }
function Link({to, children, className}){ return <a href={to} className={className} onClick={e=>{e.preventDefault(); navigate(to)}}>{children}</a> }
function Logo({compact=false}){return <div className="logo-lockup"><div className="logo-mark"><span>V</span></div>{!compact&&<div><strong>Valora<span>IQ</span></strong><small>Real Estate Intelligence</small></div>}</div>}

function PublicNav(){return <header className="public-nav"><Link to="/" className="plain"><Logo/></Link><nav><a href="/#workflows">Workflows</a><a href="/#features">Features</a><a href="/#pricing">Pricing</a><Link to="/login">Log in</Link><Link className="btn small gold" to="/signup">Start free</Link></nav></header>}
function Landing(){return <><PublicNav/><main><section className="hero"><div className="hero-grid"><div><p className="eyebrow">Professional Real Estate Intelligence Workspace</p><h1>One platform. Two workflows. Cleaner real estate decisions.</h1><p className="hero-copy">ValoraIQ helps appraisers build defensible valuation support and helps agents create persuasive CMA and listing presentations from the same market intelligence engine.</p><div className="hero-actions"><Link className="btn gold" to="/signup">Start building →</Link><Link className="btn glass" to="/appraiser">View demo dashboard</Link></div></div><div className="hero-preview"><div className="preview-header"><span/><span/><span/></div><div className="preview-title">Market Snapshot</div><div className="metric-grid three"><div><b>$425k</b><span>Median Sold</span></div><div><b>18</b><span>DOM</span></div><div><b>97.4%</b><span>List/Sale</span></div></div><div className="fake-chart">{[42,55,48,68,61,78,90].map(h=><i key={h} style={{height:`${h}%`}}/> )}</div><div className="preview-card"><b>Professional-use positioning</b><span>Market evidence, workflow support, and presentation outputs without replacing professional judgment.</span></div></div></div></section><section className="section" id="workflows"><p className="eyebrow center">Persona-specific dashboards</p><h2>Appraisers and agents should not see the same product.</h2><div className="workflow-cards"><article><h3>Appraiser Workspace</h3><p>Subject, MLS import, Q/C analyzer, market conditions, comp ranking, site value, adjustments, reconciliation, narrative, and workfile export.</p><Link to="/appraiser">Open appraiser demo</Link></article><article><h3>Agent/Broker Workspace</h3><p>Property overview, market snapshot, pricing strategy, active/pending/sold intelligence, seller net sheet, renovation ROI, listing presentation, and CMA export.</p><Link to="/agent">Open agent demo</Link></article></div></section><section className="section" id="features"><p className="eyebrow center">Core platform</p><h2>From raw MLS data to clear, client-ready outputs.</h2><div className="feature-grid">{['MLS Import','Comp Ranking + Geocoding','Q/C Analyzer','Market Conditions Modifier','Site / Land Value','AI Workflow Support'].map(t=><div className="feature-card" key={t}><div className="glyph">✦</div><h3>{t}</h3><p>Premium workflow support designed for real estate professionals.</p></div>)}</div></section><section className="section pricing" id="pricing"><p className="eyebrow center">Pricing preview</p><h2>Start with the workflow. Add cloud accounts next.</h2><p className="muted max center-block">Auth, database persistence, billing, teams, and saved cloud projects are ready for the next Supabase phase.</p></section></main></>}
function Auth({type}){return <><PublicNav/><main className="auth-page"><section className="auth-card"><p className="eyebrow">{type==='login'?'Welcome back':'Start free'}</p><h1>{type==='login'?'Log in to ValoraIQ':'Create your workspace'}</h1>{type==='signup'&&<input placeholder="Name"/>}<input placeholder="Email"/><input placeholder="Password" type="password"/><button className="btn gold full" onClick={()=>navigate(type==='login'?'/appraiser':'/agent')}>{type==='login'?'Continue to demo workspace':'Create demo workspace'}</button><p className="muted">Supabase auth will replace this prototype screen in the next phase.</p></section></main></>}

const appraiserTabs=['Dashboard','Projects','Subject Property','MLS Import','Q/C Analyzer','Market Conditions','Comp Ranking','Site / Land Value','Adjustment Grid','Reconciliation','Narrative','Photos / Exhibits','AI Assistant','Export Workfile'];
const agentTabs=['Dashboard','Projects','Property Overview','MLS Import','Market Snapshot','Pricing Strategy','Comp Ranking','Seller Net Sheet','Renovation ROI','Listing Presentation','Photos','AI Assistant','CMA Export'];
function slug(s){return s.toLowerCase().replace(/\//g,'').replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function iconFor(t){ if(t.includes('Import')) return '⬆'; if(t.includes('Market')) return '↗'; if(t.includes('Export')) return '⇩'; if(t.includes('Project')) return '▣'; if(t.includes('AI')) return '✦'; if(t.includes('Photo')) return '◉'; if(t.includes('Net')) return '$'; if(t.includes('Comp')) return '★'; if(t.includes('Q/C')) return '◆'; if(t.includes('Site')) return '◌'; return '⌂'; }

const sampleSales = [
  {address:'123 Maple Street',city:'Greenville, SC',status:'Sold',sale_price_n:425000,gla_n:2050,site_sf_n:9100,year_built_n:2001,sale_date:'2025-01-15',quality:'Q3',condition:'C3',garage:'2-Car Attached',basement:'None',pool:'No',dom:12,lat:34.8526,lon:-82.3940},
  {address:'456 Oak Avenue',city:'Greenville, SC',status:'Sold',sale_price_n:438000,gla_n:2140,site_sf_n:9800,year_built_n:1998,sale_date:'2025-02-21',quality:'Q3',condition:'C2',garage:'2-Car Attached',basement:'Partial Finished',pool:'No',dom:8,lat:34.8610,lon:-82.3820},
  {address:'789 Pine Road',city:'Greenville, SC',status:'Sold',sale_price_n:407500,gla_n:1905,site_sf_n:8500,year_built_n:2004,sale_date:'2025-03-05',quality:'Q4',condition:'C3',garage:'2-Car Attached',basement:'None',pool:'No',dom:18,lat:34.8420,lon:-82.4050},
  {address:'321 Elm Drive',city:'Greenville, SC',status:'Pending',sale_price_n:449900,gla_n:2210,site_sf_n:10200,year_built_n:2002,sale_date:'2025-04-18',quality:'Q3',condition:'C3',garage:'2-Car Attached',basement:'Full Finished',pool:'Yes',dom:6,lat:34.8660,lon:-82.3970},
  {address:'654 Cedar Lane',city:'Greenville, SC',status:'Active',sale_price_n:459000,gla_n:2260,site_sf_n:10500,year_built_n:2000,sale_date:'2025-05-07',quality:'Q3',condition:'C2',garage:'3-Car Attached',basement:'None',pool:'No',dom:21,lat:34.8720,lon:-82.3880}
];
const defaultSubject={address:'100 Valora Way',city:'Greenville, SC',effdate:'2025-05-20',gla:2100,site:9500,year:2000,beds:3,baths:2,garage:'2-Car Attached',basement:'None',pool:'No',qual:'Q3',cond:'C3',value:435000,lat:34.8526,lon:-82.3940};

function DashboardShell({persona}){const [tab,setTab]=useState('Dashboard'); const [collapsed,setCollapsed]=useState(false); const [subject,setSubject]=useState(defaultSubject); const [sales,setSales]=useState(sampleSales); const isAppraiser=persona==='appraiser'; const tabs=isAppraiser?appraiserTabs:agentTabs; useEffect(()=>{const parts=location.pathname.split('/'); if(parts[2]){const match=tabs.find(t=>slug(t)===parts[2]); if(match) setTab(match)}},[persona]); function setRoute(t){setTab(t); window.history.pushState({},'',`/${persona}${t==='Dashboard'?'':'/'+slug(t)}`)} return <div className={`dashboard-shell ${collapsed?'is-collapsed':''}`}><aside className="sidebar"><Logo compact={collapsed}/><div className="mode-toggle"><button className={isAppraiser?'active':''} onClick={()=>navigate('/appraiser')}>Appraiser</button><button className={!isAppraiser?'active':''} onClick={()=>navigate('/agent')}>Agent/Broker</button></div><div className="nav-section-label">{isAppraiser?'Appraiser Workflow':'Agent Workflow'}</div><nav className="side-nav">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setRoute(t)}><span className="nav-icon">{iconFor(t)}</span><span>{t}</span></button>)}</nav><button className="collapse-btn" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'Expand':'Collapse'} sidebar</button></aside><main className="dashboard-main"><header className="topbar"><button className="icon-btn" onClick={()=>setCollapsed(v=>!v)}>☰</button><div><strong>{isAppraiser?'Appraiser Workspace':'Agent/Broker Workspace'}</strong><span>{isAppraiser?'Defensible valuation support':'Listing and pricing intelligence'}</span></div><div className="topbar-actions"><button className="btn ghost">Help</button><button className="avatar">VQ</button></div></header><Workspace persona={persona} tab={tab} subject={subject} setSubject={setSubject} sales={sales} setSales={setSales}/></main></div>}
function Workspace({persona,tab,subject,setSubject,sales,setSales}){ if(tab==='Dashboard') return persona==='appraiser'?<AppraiserHome sales={sales}/>:<AgentHome sales={sales}/>; if(tab==='Projects') return <Projects persona={persona}/>; if(tab==='Subject Property'||tab==='Property Overview') return <SubjectForm persona={persona} subject={subject} setSubject={setSubject}/>; if(tab.includes('Import')) return <ImportData persona={persona} sales={sales} setSales={setSales}/>; if(tab==='Q/C Analyzer') return <QCAnalyzer sales={sales} subject={subject}/>; if(tab==='Market Conditions'||tab==='Market Snapshot') return <MarketConditions persona={persona} sales={sales}/>; if(tab==='Comp Ranking') return <CompRanking subject={subject} setSubject={setSubject} sales={sales} setSales={setSales}/>; if(tab==='Site / Land Value') return <SiteValue/>; if(tab==='Adjustment Grid') return <Adjustments/>; if(tab==='Reconciliation') return <Panel title="Reconciliation" eyebrow="Appraiser Only" copy="Review adjusted sale range, comp reliability, gross/net adjustment ratios, and final opinion support." metrics={['$421k Low','$438k Weighted','$452k High']}/>; if(tab==='Narrative') return <Narrative/>; if(tab.includes('Pricing')) return <Pricing/>; if(tab.includes('Seller Net')) return <SellerNet/>; if(tab.includes('Renovation')) return <Panel title="Renovation ROI" eyebrow="Agent Only" copy="Compare potential pricing lift from common pre-list improvements against estimated cost and market appeal."/>; if(tab.includes('Presentation')) return <ExportLike title="Seller Presentation Builder" items={['Market Snapshot','Pricing Strategy','Seller Net Sheet','Renovation ROI']}/>; if(tab.includes('Photo')) return <Photos persona={persona}/>; if(tab.includes('AI')) return <Assistant persona={persona}/>; if(tab.includes('Export')||tab.includes('CMA')) return <ExportLike title={persona==='appraiser'?'Workfile Export':'CMA & Presentation Export'} items={persona==='appraiser'?['Subject Summary','Market Conditions','Q/C Analysis','Comp Ranking','Site Value','Adjustment Grid','Reconciliation','Narrative Addendum','Photo Exhibits']:['Seller Presentation','CMA Summary','Pricing Strategy','Seller Net Sheet','Renovation ROI','Comp Pages']}/>; return <Panel title={tab} eyebrow="Workspace" copy="This page is now separated by persona and ready for the Supabase persistence phase."/> }

function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0)}
function fmt(n,d=0){return Number.isFinite(Number(n))?Number(n).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—'}
function median(arr){const clean=arr.map(Number).filter(n=>Number.isFinite(n)).sort((a,b)=>a-b); if(!clean.length)return 0; const m=Math.floor(clean.length/2); return clean.length%2?clean[m]:(clean[m-1]+clean[m])/2;}
function toNum(v){const n=parseFloat(String(v??'').replace(/[$,]/g,'')); return Number.isFinite(n)?n:0;}
function monthsIndex(d){const dt=new Date(d); if(isNaN(dt)) return null; return dt.getFullYear()*12+dt.getMonth();}
function monthsBetween(a,b){const ia=monthsIndex(a), ib=monthsIndex(b); return ia===null||ib===null?0:Math.abs(ia-ib)}
function ratingNum(r){const m=String(r||'').match(/(\d)/); return m?Number(m[1]):null}
function distanceMiles(lat1,lon1,lat2,lon2){const vals=[lat1,lon1,lat2,lon2].map(Number); if(vals.some(v=>!Number.isFinite(v))) return null; const R=3958.8,toRad=d=>d*Math.PI/180; const dLat=toRad(vals[2]-vals[0]),dLon=toRad(vals[3]-vals[1]); const a=Math.sin(dLat/2)**2+Math.cos(toRad(vals[0]))*Math.cos(toRad(vals[2]))*Math.sin(dLon/2)**2; return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function distanceScore(m){ if(m===null)return null; if(m<=.25)return 100; if(m<=.5)return 95; if(m<=1)return 88; if(m<=2)return 75; if(m<=3)return 62; if(m<=5)return 45; if(m<=10)return 25; return 10;}
function normalizeFeature(v){return String(v||'').toLowerCase().replace(/[^a-z0-9.]+/g,' ').trim()}
function garageCount(v){const t=normalizeFeature(v); if(!t||t==='none'||t==='no')return 0; const m=t.match(/(\d+(?:\.\d+)?)/); if(m)return Number(m[1]); if(t.includes('one'))return 1; if(t.includes('two'))return 2; if(t.includes('three'))return 3; if(t.includes('carport'))return 1; return null;}
function matchScore(a,b){const s=normalizeFeature(a),c=normalizeFeature(b); if(!s||!c)return null; return s===c?100:45;}
function scoreComp(comp,subject,w){let score=0,total=0; const add=(raw,wt)=>{if(raw!==null&&Number.isFinite(raw)&&wt>0){score+=raw*wt; total+=wt;}}; if(subject.gla&&comp.gla_n){const pct=Math.abs(comp.gla_n-subject.gla)/subject.gla; add(Math.max(0,100-pct*400),w.gla)} const dist=distanceMiles(subject.lat,subject.lon,comp.lat,comp.lon); add(distanceScore(dist),w.distance); if(subject.effdate&&comp.sale_date){add(Math.max(0,100-monthsBetween(subject.effdate,comp.sale_date)*5),w.date)} if(subject.site&&comp.site_sf_n){const pct=Math.abs(comp.site_sf_n-subject.site)/subject.site; add(Math.max(0,100-pct*300),w.site)} if(subject.year&&comp.year_built_n){add(Math.max(0,100-Math.abs(comp.year_built_n-subject.year)*3),w.year)} const sg=garageCount(subject.garage),cg=garageCount(comp.garage); add(sg===null||cg===null?null:Math.max(0,100-Math.abs(sg-cg)*35),w.garage); add(matchScore(subject.basement,comp.basement),w.basement); add(matchScore(subject.pool,comp.pool),w.pool); const sq=ratingNum(subject.qual),cq=ratingNum(comp.quality); add(sq&&cq?Math.max(0,100-Math.abs(sq-cq)*30):null,w.qual); const sc=ratingNum(subject.cond),cc=ratingNum(comp.condition); add(sc&&cc?Math.max(0,100-Math.abs(sc-cc)*25):null,w.cond); return total?score/total:0;}

function KPI({label,value,helper}){return <div className="kpi"><div className="kpi-icon">✦</div><div><span>{label}</span><strong>{value}</strong><small>{helper}</small></div></div>}
function AppraiserHome({sales}){return <div className="dash-page"><section className="welcome"><p className="eyebrow">Good morning</p><h1>Appraiser intelligence workspace</h1><p>Build support for Q/C analysis, market conditions, comparable selection, site value, adjustments, reconciliation, and workfile exports.</p></section><div className="kpi-row"><KPI label="Active Projects" value="7" helper="2 due this week"/><KPI label="Imported Sales" value={sales.length} helper="current project"/><KPI label="Reports Generated" value="9" helper="workfile PDFs"/><KPI label="Last Market Study" value="May 18" helper="rolling trend ready"/></div><div className="two-col"><ProjectTable/><QuickActions persona="appraiser"/></div><section className="panel-card"><h2>Professional Use Only</h2><p className="muted">ValoraIQ provides market analysis and valuation support. Appraisers remain responsible for all appraisal conclusions.</p></section></div>}
function AgentHome({sales}){return <div className="dash-page"><section className="welcome"><p className="eyebrow">Good morning</p><h1>Agent/Broker pricing workspace</h1><p>Build better listing conversations with market snapshots, comp ranking, pricing strategy, seller net, and CMA exports.</p></section><div className="kpi-row"><KPI label="Listing Projects" value="11" helper="4 active presentations"/><KPI label="Imported Records" value={sales.length} helper="active/pending/sold"/><KPI label="CMA Exports" value="14" helper="this month"/><KPI label="Avg DOM" value="18" helper="sample market"/></div><div className="two-col"><Pricing compact/><QuickActions persona="agent"/></div></div>}
function ProjectTable(){const rows=[['123 Maple Street','Appraisal','In Progress','$438k'],['456 Oak Avenue','CMA','Review','$510k'],['789 Pine Road','Market Study','Draft','$425k']]; return <div className="table-card"><div className="card-head"><h2>Recent Projects</h2><button>View all →</button></div><table><thead><tr><th>Project</th><th>Type</th><th>Status</th><th>Indication</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b><span>Updated recently</span></td><td>{r[1]}</td><td><em>{r[2]}</em></td><td>{r[3]}</td></tr>)}</tbody></table></div>}
function QuickActions({persona}){const actions=persona==='appraiser'?['New Appraisal Project','Import MLS Data','Run Q/C Analyzer','Run Market Conditions','Rank Comparables','Export Workfile PDF']:['New CMA Project','Import MLS Data','Rank Comparables','Build Seller Presentation','Create Seller Net Sheet']; return <div className="quick-card"><h2>Quick Actions</h2>{actions.map(a=><button key={a}>{a}<span>›</span></button>)}</div>}
function Projects({persona}){
  const projects=['123 Maple Street','456 Oak Avenue','789 Pine Road','321 Elm Drive','654 Cedar Lane'];
  const openPath = persona==='appraiser' ? `/${persona}/subject-property` : `/${persona}/property-overview`;
  return <div className="dash-page"><section className="panel-card row-between"><div><p className="eyebrow">Projects</p><h1>{persona==='appraiser'?'Appraisal Projects':'CMA & Listing Projects'}</h1><p className="muted max">These are local demo projects for now. The Open buttons now route into the active workflow page. Supabase will later persist projects, uploads, notes, exports, and team access.</p></div><button className="btn gold" onClick={()=>navigate(openPath)}>+ New Project</button></section><div className="project-grid">{projects.map((proj,i)=><article className="project-card" key={proj}><span>{persona==='appraiser'?'Appraisal':i%2?'Listing CMA':'Seller Strategy'}</span><h3>{proj}</h3><p>Updated {i+1} day{i?'s':''} ago</p><div><em>{i%3===0?'In Progress':i%3===1?'Review':'Draft'}</em><button className="btn ghost small" onClick={()=>navigate(openPath)}>Open</button></div></article>)}</div></div>
}

function SubjectForm({persona,subject,setSubject}){
  const [saved,setSaved]=useState(false); const [message,setMessage]=useState('');
  const fields=[['address','Street Address'],['city','City, State, ZIP'],['effdate','Effective / Analysis Date','date'],['gla','GLA','number'],['site','Site Area SF','number'],['year','Year Built','number'],['beds','Bedrooms','number'],['baths','Baths','number'],['garage','Garage'],['basement','Basement'],['pool','Pool'],['qual','Quality Rating'],['cond','Condition Rating'],['value','Opinion / Target Value','number']];
  function update(key,type,value){setSaved(false); setSubject({...subject,[key]:type==='number'?toNum(value):value});}
  function save(){setSaved(true); setMessage('Subject profile saved for this session. This now drives comp ranking, market analysis, site value, and exports.');}
  async function geo(){const q=encodeURIComponent([subject.address,subject.city].filter(Boolean).join(', ')); if(!q){setMessage('Enter a street address and city before geocoding.'); return;} setMessage('Geocoding subject address...'); try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${q}&limit=1`); const d=await r.json(); if(d?.[0]){setSubject({...subject,lat:Number(d[0].lat),lon:Number(d[0].lon)}); setSaved(true); setMessage('Subject geocoded and saved for this session.');} else setMessage('No geocode result found. Try a fuller address with ZIP or county.');}catch{setMessage('Geocoding failed. You can still continue without distance ranking.');}}
  return <div className="dash-page"><section className="panel-card"><p className="eyebrow">{persona==='appraiser'?'Subject Property':'Property Overview'}</p><h1>{persona==='appraiser'?'Subject Property Profile':'Listing Property Profile'}</h1><p className="muted max">This is an active page now. Edit the property, save it, and geocode it. The saved values carry into comp ranking, market comparison, adjustment support, site value, and exports during this session.</p><div className="form-grid">{fields.map(([key,label,type='text'])=><label key={key}>{label}<input type={type} value={subject[key]??''} onChange={e=>update(key,type,e.target.value)}/></label>)}</div><div className="btn-row"><button className="btn gold" onClick={save}>Save Subject</button><button className="btn ghost" onClick={geo}>Save & Geocode Subject</button><button className="btn ghost" onClick={()=>navigate(`/${persona}/mls-import`)}>Continue to MLS Import</button></div><div className={`status-banner ${saved?'success':''}`}>{message || `Coordinates: ${subject.lat?`${fmt(subject.lat,5)}, ${fmt(subject.lon,5)}`:'not geocoded yet'}`}</div></section></div>
}

const FIELD_ALIASES={address:['address','property address','street address','full address','street'],city:['city','municipality','city state zip'],state:['state'],zip:['zip','zipcode','zip code','postal code'],status:['status','mls status'],sale_price:['sale price','close price','sold price','list price','price','sp','lp'],sale_date:['sale date','close date','sold date','closing date'],gla:['gla','living area','sqft','sf','sq ft','above grade'],site_sf:['site size','lot size','lot sf','lot sqft','site area','acres'],year_built:['year built','yr built','built','year constructed'],quality:['quality','q rating','q'],condition:['condition','c rating','c'],garage:['garage','parking','garage spaces'],basement:['basement','bsmt'],pool:['pool'],dom:['dom','days on market'],lat:['lat','latitude'],lon:['lon','lng','longitude']};
const FIELD_LABELS={address:'Address',city:'City',state:'State',zip:'ZIP',status:'Status',sale_price:'Sale Price',sale_date:'Sale Date',gla:'GLA',site_sf:'Site / Lot SF',year_built:'Year Built',quality:'Quality',condition:'Condition',garage:'Garage',basement:'Basement',pool:'Pool',dom:'DOM',lat:'Latitude',lon:'Longitude'};
function parseCSVMatrix(text){const rows=[]; let row=[],cur='',q=false; for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1]; if(c==='"'&&q&&n==='"'){cur+='"'; i++;} else if(c==='"'){q=!q;} else if(c===','&&!q){row.push(cur.trim()); cur='';} else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++; row.push(cur.trim()); if(row.some(Boolean))rows.push(row); row=[]; cur='';} else cur+=c;} row.push(cur.trim()); if(row.some(Boolean))rows.push(row); return {headers:rows[0]||[], rows:rows.slice(1)};}
function autoMapHeaders(headers){const map={}; headers.forEach((h,i)=>{const hl=h.toLowerCase().trim(); Object.entries(FIELD_ALIASES).forEach(([field,aliases])=>{if(map[field]===undefined && aliases.some(a=>hl===a||hl.includes(a)||a.includes(hl))) map[field]=String(i);});}); return map;}
function rowsFromMapping(headers,rows,map){return rows.map((cells,i)=>{const get=f=>map[f]!==undefined&&map[f]!==''?cells[Number(map[f])]||'':''; return {id:i,address:get('address'),city:get('city'),state:get('state'),zip:get('zip'),status:get('status')||'Sold',sale_price_n:toNum(get('sale_price')),gla_n:toNum(get('gla')),site_sf_n:toNum(get('site_sf')),year_built_n:toNum(get('year_built')),sale_date:get('sale_date'),quality:get('quality'),condition:get('condition'),garage:get('garage'),basement:get('basement'),pool:get('pool'),dom:toNum(get('dom')),lat:toNum(get('lat'))||null,lon:toNum(get('lon'))||null};}).filter(r=>r.address||r.sale_price_n||r.gla_n)}
function ImportData({persona,sales,setSales}){
  const [headers,setHeaders]=useState([]),[rawRows,setRawRows]=useState([]),[mapping,setMapping]=useState({}),[preview,setPreview]=useState(sales),[fileName,setFileName]=useState('');
  async function handle(e){const f=e.target.files?.[0]; if(!f)return; const text=await f.text(); const parsed=parseCSVMatrix(text); const m=autoMapHeaders(parsed.headers); setHeaders(parsed.headers); setRawRows(parsed.rows); setMapping(m); setPreview(rowsFromMapping(parsed.headers,parsed.rows,m)); setFileName(f.name);}
  function apply(){const records=rowsFromMapping(headers,rawRows,mapping); setPreview(records); setSales(records);}
  function updateMap(field,value){const next={...mapping,[field]:value}; setMapping(next); setPreview(rowsFromMapping(headers,rawRows,next));}
  return <div className="dash-page"><section className="panel-card"><p className="eyebrow">MLS Import</p><h1>{persona==='appraiser'?'Import appraisal sales data':'Import CMA market data'}</h1><p className="muted max">CSV import now includes a field-mapping review step before committing data. Upload the CSV, verify each field, then click Apply Mapping.</p><label className="upload-box"><strong>Click to upload MLS CSV</strong><span>Active, pending, sold, expired, or closed sales exports</span><input type="file" accept=".csv" onChange={handle}/></label><div className="btn-row"><button className="btn ghost" onClick={()=>{setHeaders([]);setRawRows([]);setMapping({});setSales(sampleSales);setPreview(sampleSales);setFileName('Demo sales')}}>Load Demo Sales</button>{fileName&&<span className="muted">Loaded: {fileName}</span>}</div></section>{headers.length>0&&<section className="panel-card"><div className="card-head"><h2>Column Mapping</h2><button className="btn gold small" onClick={apply}>Apply Mapping</button></div><p className="muted">Required for most analysis: Sale Price, Sale Date, GLA. Recommended: Address, City, Site, Year Built, Quality, Condition, Garage, Basement, Pool, DOM.</p><div className="mapper-grid">{Object.keys(FIELD_LABELS).map(field=><label key={field}>{FIELD_LABELS[field]}<select value={mapping[field]??''} onChange={e=>updateMap(field,e.target.value)}><option value="">— Not in CSV —</option>{headers.map((h,i)=><option key={h+i} value={i}>{h}</option>)}</select></label>)}</div></section>}{preview.length>0&&<section className="table-card"><div className="card-head"><h2>{headers.length?'Preview Records':'Imported Records'}</h2><span>{preview.length} rows detected</span></div><table><thead><tr><th>Address</th><th>Status</th><th>Price</th><th>Date</th><th>GLA</th><th>Site</th><th>Year</th><th>Q</th><th>C</th></tr></thead><tbody>{preview.slice(0,20).map((r,i)=><tr key={i}><td>{r.address||'—'}</td><td>{r.status||'—'}</td><td>{money(r.sale_price_n)}</td><td>{r.sale_date||'—'}</td><td>{r.gla_n||'—'}</td><td>{r.site_sf_n||'—'}</td><td>{r.year_built_n||'—'}</td><td>{r.quality||'—'}</td><td>{r.condition||'—'}</td></tr>)}</tbody></table>{headers.length>0&&<button className="btn gold" onClick={apply}>Apply Mapping & Use These Records</button>}</section>}</div>
}

function QCAnalyzer({sales,subject}){const counts=(field,prefix)=>['1','2','3','4','5','6'].map(n=>{const key=prefix+n; return [key,sales.filter(s=>String(s[field]||'').toUpperCase().startsWith(key)).length]}); const q=counts('quality','Q'), c=counts('condition','C'); const qn=ratingNum(subject.qual), cn=ratingNum(subject.cond); return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Appraiser Tool Restored</p><h1>Q/C Analyzer</h1><p className="muted max">Analyze the quality and condition distribution of the comp pool, compare the subject against the market spectrum, and flag ratings that need professional review.</p><div className="qc-summary"><div><h2>Subject Quality</h2><b>{subject.qual||'—'}</b><span>{qn?'Rating captured':'Select a Q rating in Subject Property'}</span></div><div><h2>Subject Condition</h2><b>{subject.cond||'—'}</b><span>{cn?'Rating captured':'Select a C rating in Subject Property'}</span></div></div></section><section className="two-col"><Distribution title="Quality Distribution" data={q}/><Distribution title="Condition Distribution" data={c}/></section><section className="table-card"><div className="card-head"><h2>Q/C Review Flags</h2><span>{sales.length} sales reviewed</span></div><table><thead><tr><th>Sale</th><th>Q</th><th>C</th><th>Flag</th></tr></thead><tbody>{sales.slice(0,15).map((s,i)=>{const missing=!s.quality||!s.condition; const qdiff=qn&&ratingNum(s.quality)?Math.abs(ratingNum(s.quality)-qn):0; const cdiff=cn&&ratingNum(s.condition)?Math.abs(ratingNum(s.condition)-cn):0; return <tr key={i}><td>{s.address||'—'}</td><td>{s.quality||'—'}</td><td>{s.condition||'—'}</td><td><em className={missing||qdiff>1||cdiff>1?'flag-warn':'flag-good'}>{missing?'Missing rating':qdiff>1||cdiff>1?'Large Q/C spread':'Typical'}</em></td></tr>})}</tbody></table></section></div>}
function Distribution({title,data}){const max=Math.max(1,...data.map(d=>d[1])); return <section className="panel-card"><h2>{title}</h2><div className="bar-list">{data.map(([k,v])=><div key={k}><span>{k}</span><i><b style={{width:`${v/max*100}%`}}/></i><em>{v}</em></div>)}</div></section>}

function MarketConditions({persona,sales}){const [mode,setMode]=useState('rolling3'),[minSales,setMinSales]=useState(1); const series=useMemo(()=>marketSeries(sales,minSales,mode),[sales,minSales,mode]); return <div className="dash-page"><section className="panel-card"><p className="eyebrow">{persona==='appraiser'?'Market Conditions Tool Restored':'Market Snapshot'}</p><h1>{persona==='appraiser'?'Market Conditions / Rolling Modifier':'Active / Pending / Sold Market Snapshot'}</h1><p className="muted max">Rolling 3-month median, quarterly grouping, and weighted trend line options are back for thin or volatile markets.</p><div className="form-grid compact"><label>Limited Data Modifier<select value={mode} onChange={e=>setMode(e.target.value)}><option value="raw">Off — raw period medians</option><option value="rolling3">Rolling 3-month median</option><option value="quarterly">Quarterly modifier</option><option value="weighted">Weighted trend line by sale count</option></select></label><label>Minimum Sales Per Period<input type="number" value={minSales} min="1" onChange={e=>setMinSales(Number(e.target.value)||1)}/></label></div><div className="metric-grid four"><div><b>{series.monthly.toFixed(3)}%</b><span>Monthly Rate</span></div><div><b>{(series.monthly*12).toFixed(2)}%</b><span>Annualized</span></div><div><b>{series.points.length}</b><span>Periods Used</span></div><div><b>{mode}</b><span>Modifier</span></div></div></section><section className="chart-card"><h2>Median Sale Price Trend</h2><div className="line-chart">{series.points.map((p,i)=><i key={p.key+i} style={{height:`${Math.max(8,Math.min(100,(p.yMod/series.max)*100))}%`}} title={`${p.key}: ${money(p.yMod)}`}/> )}</div><div className="table-card embedded"><table><thead><tr><th>Period</th><th>Sales</th><th>Raw Median</th><th>Modified Median</th></tr></thead><tbody>{series.points.map(p=><tr key={p.key}><td>{p.key}</td><td>{p.n}</td><td>{money(p.y)}</td><td>{money(p.yMod)}</td></tr>)}</tbody></table></div></section></div>}
function periodKey(date,quarter=false){const d=new Date(date); if(isNaN(d))return null; if(quarter)return `${d.getFullYear()} Q${Math.floor(d.getMonth()/3)+1}`; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function periodIndex(key){if(key.includes('Q')){const [y,q]=key.split(' Q').map(Number); return y*12+(q-1)*3} const [y,m]=key.split('-').map(Number); return y*12+m-1}
function marketSeries(sales,minSales,mode){const quarter=mode==='quarterly'; const groups={}; sales.forEach(s=>{const k=periodKey(s.sale_date,quarter); if(!k||!s.sale_price_n)return; (groups[k]??=[]).push(s.sale_price_n)}); let pts=Object.keys(groups).sort((a,b)=>periodIndex(a)-periodIndex(b)).map(k=>({key:k,x:periodIndex(k),y:median(groups[k]),n:groups[k].length})).filter(p=>p.n>=minSales); if(pts.length<2) pts=Object.keys(groups).sort((a,b)=>periodIndex(a)-periodIndex(b)).map(k=>({key:k,x:periodIndex(k),y:median(groups[k]),n:groups[k].length})); if(mode==='rolling3'&&!quarter){pts=pts.map(p=>{const neighbors=pts.filter(q=>Math.abs(q.x-p.x)<=1); const pool=neighbors.flatMap(q=>Array(q.n).fill(q.y)); return {...p,yMod:median(pool.length?pool:[p.y])}})} else if(mode==='weighted'&&pts.length>1){const x0=pts[0].x, sw=pts.reduce((a,p)=>a+p.n,0), sx=pts.reduce((a,p)=>a+(p.x-x0)*p.n,0), sy=pts.reduce((a,p)=>a+p.y*p.n,0), sxy=pts.reduce((a,p)=>a+(p.x-x0)*p.y*p.n,0), sx2=pts.reduce((a,p)=>a+(p.x-x0)**2*p.n,0); const denom=sw*sx2-sx*sx; const b=denom?(sw*sxy-sx*sy)/denom:0; const a=sw?(sy-b*sx)/sw:0; pts=pts.map(p=>({...p,yMod:a+b*(p.x-x0)}))} else pts=pts.map(p=>({...p,yMod:p.y})); const first=pts[0],last=pts[pts.length-1]; const months=first&&last?Math.max(1,last.x-first.x):1; const monthly=first&&last&&first.yMod?((last.yMod-first.yMod)/first.yMod*100)/months:0; return {points:pts,monthly,max:Math.max(1,...pts.map(p=>p.yMod))}}

function CompRanking({subject,setSubject,sales,setSales}){const [w,setW]=useState({gla:24,distance:18,date:18,site:10,year:8,garage:7,basement:5,pool:4,qual:3,cond:3}); const [busy,setBusy]=useState(''); const ranked=useMemo(()=>sales.map(s=>({...s,_distance:distanceMiles(subject.lat,subject.lon,s.lat,s.lon),_score:scoreComp(s,subject,w)})).sort((a,b)=>b._score-a._score),[sales,subject,w]); async function geocodeOne(addr){const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(addr)}&limit=1`); const d=await r.json(); return d?.[0]?{lat:Number(d[0].lat),lon:Number(d[0].lon)}:null} async function geoSubject(){setBusy('Geocoding subject...'); const res=await geocodeOne([subject.address,subject.city].filter(Boolean).join(', ')); if(res)setSubject({...subject,...res}); setBusy('')} async function geoComps(){setBusy('Geocoding comparable sales...'); const updated=[]; for(let i=0;i<sales.length;i++){const s=sales[i]; if(s.lat&&s.lon){updated.push(s); continue;} const addr=[s.address,s.city,s.state,s.zip].filter(Boolean).join(', '); if(!addr){updated.push(s); continue;} try{const res=await geocodeOne(addr); updated.push(res?{...s,...res}:s);}catch{updated.push(s)} await new Promise(r=>setTimeout(r,650));} setSales(updated); setBusy('')} return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Comp Ranking Tool Restored</p><h1>Comparable Sale Ranking + Geocoding</h1><p className="muted max">Ranks comps by GLA, distance, date, site, age, garage, basement, pool, quality, and condition. Subject and comp geocoding use OpenStreetMap Nominatim.</p><div className="btn-row"><button className="btn gold" onClick={geoSubject}>Geocode Subject</button><button className="btn ghost" onClick={geoComps}>Geocode Comparable Sales</button>{busy&&<span className="muted">{busy}</span>}</div><div className="weight-grid">{Object.keys(w).map(k=><label key={k}>{k}<input type="number" value={w[k]} onChange={e=>setW({...w,[k]:Number(e.target.value)||0})}/></label>)}</div><div className="muted">Weight total: {Object.values(w).reduce((a,b)=>a+b,0)}</div></section><section className="rank-grid">{ranked.slice(0,12).map((s,i)=><article className="rank-card" key={i}><div className="rank-num">#{i+1}</div><div><h3>{s.address||'Address not mapped'}</h3><p>{s.city||''}</p><div className="rank-meta"><span>Score <b>{fmt(s._score,0)}</b></span><span>Price <b>{money(s.sale_price_n)}</b></span><span>GLA <b>{fmt(s.gla_n)}</b></span><span>Distance <b>{s._distance!==null?`${fmt(s._distance,2)} mi`:'—'}</b></span><span>Q/C <b>{s.quality||'—'} / {s.condition||'—'}</b></span></div>{s.lat&&s.lon&&<a className="map-link" href={`https://www.openstreetmap.org/?mlat=${s.lat}&mlon=${s.lon}#map=16/${s.lat}/${s.lon}`} target="_blank" rel="noreferrer">Open map</a>}</div></article>)}</section></div>}

function SiteValue(){const [land,setLand]=useState([{price:85000,site:9500},{price:92000,site:10500},{price:78000,site:8700}]); const [imp,setImp]=useState(350000),[total,setTotal]=useState(435000),[pct,setPct]=useState(20); const avg=land.reduce((a,r)=>a+(Number(r.price)||0)/(Number(r.site)||1),0)/land.length; const allocation=total*pct/100; const abstraction=total-imp; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Site Value Tool Restored</p><h1>Site / Land Value Support</h1><p className="muted max">Support site value using vacant land sales, allocation, and abstraction methods.</p><div className="metric-grid three"><div><b>{money(avg)}</b><span>Avg $/SF Site</span></div><div><b>{money(allocation)}</b><span>Allocation Indication</span></div><div><b>{money(abstraction)}</b><span>Abstraction Indication</span></div></div></section><section className="table-card"><div className="card-head"><h2>Vacant Land Sales</h2><button onClick={()=>setLand([...land,{price:0,site:0}])}>+ Add Sale</button></div><table><thead><tr><th>Sale Price</th><th>Site SF</th><th>$/SF</th></tr></thead><tbody>{land.map((r,i)=><tr key={i}><td><input className="cell-input" type="number" value={r.price} onChange={e=>setLand(land.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></td><td><input className="cell-input" type="number" value={r.site} onChange={e=>setLand(land.map((x,j)=>j===i?{...x,site:Number(e.target.value)}:x))}/></td><td>{money((r.price||0)/(r.site||1))}</td></tr>)}</tbody></table></section><section className="panel-card"><h2>Allocation / Abstraction</h2><div className="form-grid"><label>Total Property Value<input type="number" value={total} onChange={e=>setTotal(Number(e.target.value))}/></label><label>Allocation % to Site<input type="number" value={pct} onChange={e=>setPct(Number(e.target.value))}/></label><label>Improvement Value Estimate<input type="number" value={imp} onChange={e=>setImp(Number(e.target.value))}/></label></div></section></div>}

function Adjustments(){const lines=['Location','Site','GLA','Quality','Condition','Garage','Basement','Concessions','Market Conditions']; const [values,setValues]=useState(Object.fromEntries(lines.map(l=>[l,0]))); const total=useMemo(()=>Object.values(values).reduce((a,b)=>a+Number(b||0),0),[values]); return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Appraiser Only</p><h1>Adjustment Grid</h1><p className="muted max">Line-item support, notes, net/gross indicators, and reconciliation-ready totals.</p></section><section className="table-card"><table><thead><tr><th>Adjustment Line</th><th>Amount</th><th>Support Note</th></tr></thead><tbody>{lines.map(l=><tr key={l}><td>{l}</td><td><input className="cell-input" type="number" value={values[l]} onChange={e=>setValues({...values,[l]:e.target.value})}/></td><td><input className="cell-input wide" placeholder="Market-derived support or paired-sale note"/></td></tr>)}</tbody></table><div className="adjustment-total">Net Adjustment: <strong>{money(total)}</strong></div></section></div>}
function Panel({title,eyebrow,copy,metrics}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted max">{copy}</p>{metrics&&<div className="metric-grid three">{metrics.map(m=><div key={m}><b>{m.split(' ')[0]}</b><span>{m.split(' ').slice(1).join(' ')}</span></div>)}</div>}</section></div>}
function Narrative(){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Appraiser Only</p><h1>Narrative Builder</h1><p className="muted max">Generate editable report language for market conditions, comp selection, concessions, reconciliation, and data quality.</p><textarea className="big-text" defaultValue="The comparable sales selected represent the best available market evidence based on proximity, date of sale, physical similarity, and overall reliability."/></section></div>}
function Pricing({compact=false}){return <section className={`strategy-card ${compact?'':'large'}`}><p className="eyebrow">Agent Only</p><h1>Pricing Strategy Snapshot</h1><div className="metric-grid three"><div><b>$510k</b><span>Recommended List</span></div><div><b>$495k–$525k</b><span>Likely Contract Range</span></div><div><b>14–21</b><span>Expected DOM</span></div></div><p>Position pricing slightly below current active competition while staying aligned with pending momentum and closed-sale proof.</p></section>}
function SellerNet(){const [price,setPrice]=useState(510000),[mort,setMort]=useState(310000),[comm,setComm]=useState(5.5),[cost,setCost]=useState(6500); const net=price-mort-(price*comm/100)-cost; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Agent Only</p><h1>Seller Net Sheet</h1><div className="form-grid"><label>Sale Price<input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Mortgage Payoff<input type="number" value={mort} onChange={e=>setMort(+e.target.value)}/></label><label>Commission %<input type="number" value={comm} onChange={e=>setComm(+e.target.value)}/></label><label>Closing Costs<input type="number" value={cost} onChange={e=>setCost(+e.target.value)}/></label></div><div className="net-result">Estimated Seller Net <strong>{money(net)}</strong></div></section></div>}
function ExportLike({title,items}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Export Center</p><h1>{title}</h1><p className="muted max">PDF export preview is structured. Final branded PDF generation can be upgraded after backend setup.</p><div className="check-list">{items.map(i=><label key={i}><input type="checkbox" defaultChecked/> {i}</label>)}</div><button className="btn gold">Generate Preview Export</button></section></div>}
function Photos({persona}){return <div className="dash-page"><section className="panel-card"><p className="eyebrow">Photos & Exhibits</p><h1>{persona==='appraiser'?'Subject and Comp Exhibits':'Listing Photo Organizer'}</h1><p className="muted max">Drag/drop UI is ready. Supabase Storage will later store images securely by project.</p><div className="photo-grid">{['Subject Front','Kitchen','Comparable 1','Map Exhibit'].map(x=><div className="photo-tile" key={x}><span>◉</span><b>{x}</b></div>)}</div></section></div>}
function Assistant({persona}){const prompts=persona==='appraiser'?['Draft market conditions narrative','Summarize concession evidence','Identify outlier comps','Explain reconciliation support']:['Create seller talking points','Explain pricing strategy','Summarize active competition','Write listing presentation intro']; return <div className="dash-page"><section className="panel-card"><p className="eyebrow">AI Workflow Assistant</p><h1>{persona==='appraiser'?'Narrative and evidence support':'Seller conversation support'}</h1><p className="muted max">Positioned as workflow assistance, not automated valuation or appraisal replacement.</p><div className="prompt-grid">{prompts.map(p=><button key={p}>{p}</button>)}</div><textarea className="big-text" placeholder="Ask ValoraIQ to summarize evidence, explain a pricing position, or draft editable language..."/></section></div>}
function App(){const path=usePath(); if(path==='/login') return <Auth type="login"/>; if(path==='/signup') return <Auth type="signup"/>; if(path.startsWith('/appraiser')) return <DashboardShell persona="appraiser"/>; if(path.startsWith('/agent')) return <DashboardShell persona="agent"/>; return <Landing/>}

createRoot(document.getElementById('root')).render(<App/>);
